// web/src/app/group/DeleteNode.tsx
import * as React from "react";
import IApronDeviceGroup from "../../models/ApronDeviceGroup";

interface IDeleteNodeProps {
    group: IApronDeviceGroup;
    node: IApronDeviceGroup;
    deleteNode(groupId: number, nodeId: number);
}

export default class DeleteNode extends React.Component<IDeleteNodeProps, any> {
    public render() {
        const { node } = this.props;
        return (
            <div className="col col-md-4" style={{marginBottom: "1rem"}} key={node.ID}>
                <div className="input-group input-group-sm">
                    <span className="input-group-btn">
                        <a tabIndex={-1} className="btn btn-sm btn-danger"
                            onClick={this.onClick}>Delete</a>
                    </span>
                    <input value={node.Name}
                        className="form-control form-control-sm"
                        readOnly={true} type="text" />
                </div>
            </div>
        );
    }

    private onClick = (event: React.FormEvent<HTMLAnchorElement>) => {
        event.preventDefault();
        this.props.deleteNode(this.props.group.ID, this.props.node.ID);
    }
}

// web/src/group/deleteNode.vue
<template>
	<div class="row">
		<div class="col col-md-4" v-for="node in group.Nodes">
			<div class="input-group input-group-sm">
				<span class="input-group-btn">
					<a tabindex="-1" class="btn btn-sm btn-danger" @click.stop="deleteNode(node)"
						:class="{ disabled: group.ActionInProgress }">Delete</a>
				</span>
				<input :value="node.Name" 
					:class="{ disabled: group.ActionInProgress }"
					class="form-control form-control-sm" 
					readonly="readonly" type="text" />
			</div>
		</div>
	</div>
</template>

<script>
module.exports = require('./deleteNode.ts').default.vueComponentOptions
</script>

<style scoped>
.col { margin-bottom: 1rem; }
</style>
